# Generated by Django 4.0.4 on 2022-04-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_bid_category_lot_watchlist_profile_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='item_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.lot'),
        ),
    ]
