# Generated by Django 4.0.4 on 2022-06-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_lot_end_auction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auctions',
        ),
    ]
